site_name: Computer Engineering Docs
site_url: https://docs.cmpe.boun.edu.tr/
site_description: "Documentation for Computer Engineering Department at Boğaziçi University"
site_author: bouncmpe

copyright: Copyright &copy; 1982 - 2023 Department of Computer Engineering

docs_dir: content
repo_name: bouncmpe/docs
repo_url: https://github.com/bouncmpe/docs
edit_uri: edit/main/content/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    edit: material/pencil
    view: material/eye
  language: "en"
  font:
    text: Inter
  palette:
    scheme: south-campus
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view

plugins:
  - git-revision-date-localized:
      type: iso_date
  - search:
      lang:
        - en
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - meta
  - tables
  - toc:
      permalink: "#"
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Bogazici_CmpE
    - icon: fontawesome/brands/github
      link: https://github.com/bouncmpe

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Undergraduate Program:
      - undergraduate/index.md
      - Incoming Students: undergraduate/incoming-students.md
      - Semester Registration: undergraduate/registration.md
      - Courses: undergraduate/courses.md
      - In-Service Training:
          - undergraduate/training/index.md
          - Overview: undergraduate/training/index.md
          - Rules and Regulations: undergraduate/training/bylaws.md
          - Frequently Asked Questions: undergraduate/training/faq.md
      - Senior Projects:
          - undergraduate/senior-projects/index.md
          - Overview: undergraduate/senior-projects/index.md
          - Rules and Regulations: undergraduate/senior-projects/regulations.md
      - Graduation Requirements: undergraduate/graduation.md
      - Double Major Program: undergraduate/double-major.md
      - Minor Degree Program: undergraduate/minor-degree.md
      - Student Exchange Programs: undergraduate/student-exchange.md

  - MS Program:
      - ms-program/index.md
      - Application:
          - ms-program/application/index.md
          - Overview: ms-program/application/index.md
          - Interview: ms-program/application/interview.md
          - Evaluation: ms-program/application/evaluation.md
      - Admitted Students: ms-program/admitted.md
      - Semester Registration: ms-program/registration.md
      - Courses: ms-program/courses.md
      - Thesis: ms-program/thesis.md

  - PhD Program:
      - phd-program/index.md
      - Application:
          - phd-program/application/index.md
          - Overview: phd-program/application/index.md
          - Interview: phd-program/application/interview.md
          - Evaluation: phd-program/application/evaluation.md
      - Admitted Students: phd-program/admitted.md
      - Semester Registration: phd-program/registration.md
      - Courses: phd-program/courses.md
      - Qualification: phd-program/qualification.md
      - Thesis: phd-program/thesis.md

  - Resources:
      - Tutorials:
          - tutorials/index.md
          - Fantastic Beasts and Where to Find Them: tutorials/index.md

  - About:
      - Student Petitions: about/student-petitions.md
      - Procedure against Cheating: about/cheating-behavior.md
      - Publication Copyright Policies: about/copyright-policies.md
